export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CART_ACTION = {
  SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
  SET_CART_ITEMS: 'SET_CART_ITEMS',
};

export const SET_CATEGORIES_MAP = "SET_CATEGORIES_MAP";

